### ISSUE TITLE
Hackage revision

### ISSUE THREAD

**Issue by hasufell** [nikita-volkov/focus#11]
focus-1.0.3.1 does not build with GHC-9.8.X. This is fixed in focus-1.0.3.2.

@Bodigrim can you make a revision restricting `base < 4.19` in focus-1.0.3.1?

```
$ cabal build -w ghc-9.8
Resolving dependencies...
Build profile: -w ghc-9.8.1 -O1
In order, the following will be built (use -v for more details):
 - focus-1.0.3.1 (lib) (first run)
Configuring library for focus-1.0.3.1..
Preprocessing library for focus-1.0.3.1..
Building library for focus-1.0.3.1..
[1 of 2] Compiling Focus.Prelude    ( library/Focus/Prelude.hs, /home/hasufell/tmp/focus-1.0.3.1/dist-newstyle/build/x86_64-linux/ghc-9.8.1/focus-1.0.3.1/build/Focus/Prelude.o, /home/hasufell/tmp/focus-1.0.3.1/dist-newstyle/build/x86_64-linux/ghc-9.8.1/focus-1.0.3.1/build/Focus/Prelude.dyn_o )

library/Focus/Prelude.hs:2:5: error: [GHC-69158]
    Conflicting exports for ‘unzip’:
       ‘module Exports’ exports ‘Exports.unzip’
         imported from ‘Data.Functor’ at library/Focus/Prelude.hs:33:1-30
       ‘module Exports’ exports ‘Exports.unzip’
         imported from ‘Prelude’ at library/Focus/Prelude.hs:74:1-191
         (and originally defined in ‘GHC.List’)
  |
2 |   ( module Exports,
  |     ^^^^^^^^^^^^^^
Error: cabal: Failed to build focus-1.0.3.1.
```

**Comment by nikita-volkov** [comment]
Done
